title: "Balanced: Blog"
name: Balanced Blog
description: Balanced Blog
url: https://umran.github.io

markdown: kramdown
highlighter: true
permalink: /:title

lsi: false
paginate: 24

generic_cover_image: /img/blogimages/generic-cover.jpg
generic_image: /img/blogimages/generic.jpg

exclude:
- CNAME
